import type { AssessmentData } from './schema';
import type { ApproachOptions } from './scoring';

export function generateBlueprint(data: AssessmentData, approach: ApproachOptions): string {
  let md = `# Architecture Blueprint & Technical Checklist\n\n`;
  md += `Generated by AI Approach Calculator based on initial client assessment.\n\n`;
  md += `---\n\n`;

  // 1. Core Architecture Pattern
  md += `## 1. Core Architecture & Hosting\n`;
  if (approach === 'OS_Stack') {
    md += `- [ ] **Compute**: Provision GPU instances (e.g., AWS EC2 P4d / Azure NDv4) for self-hosting LLMs.\n`;
    md += `- [ ] **LLM Engine**: Deploy \`vLLM\` or \`Ollama\` for efficient, high-throughput inference.\n`;
    md += `- [ ] **Orchestration**: Setup \`LangGraph\` or \`AutoGen\` via FastAPI (Python/uv) microservices.\n`;
  } else if (approach === 'Managed_Cloud') {
    md += `- [ ] **Compute**: Provision Azure Container Apps or AWS ECS (Serverless consumption tier).\n`;
    md += `- [ ] **LLM Engine**: Setup Azure OpenAI / Google Vertex AI endpoints with provisioned throughput.\n`;
    md += `- [ ] **Orchestration**: Deploy lightweight Python (FastAPI/LangChain) API gateways.\n`;
  } else {
    md += `- [ ] **Compute**: Provision standard VPS (e.g., DigitalOcean / AWS EC2 T-series) or use SaaS.\n`;
    md += `- [ ] **Pipeline Engine**: Deploy \`n8n\` using Docker Compose (or use n8n Cloud mapping).\n`;
  }

  // 2. Data Layer (RAG & Storage)
  md += `\n## 2. Data Layer & RAG Strategy\n`;
  if (data.dataVolume === 'Massive (Millions of records or huge databases)') {
    md += `- [ ] **Vector Storage**: Provision a scalable, distributed cluster (e.g., \`Milvus\`, \`Qdrant\`, or \`Pinecone Enterprise\`).\n`;
    md += `- [ ] **Relational DB**: PostgreSQL or Distributed SQL (CockroachDB/TiDB) for metadata tracking.\n`;
  } else {
    md += `- [ ] **Vector Storage**: Provision \`Qdrant\` (single node) or \`Supabase\` with \`pgvector\`.\n`;
    md += `- [ ] **Relational DB**: Standard PostgreSQL (e.g., via Supabase or Neon).\n`;
  }

  if (data.dataType === 'Complex mixed data (Text, Images, Audio)') {
    md += `- [ ] **Data Pipeline**: Implement Multi-modal ETL workers (e.g., using \`Unstructured.io\`).\n`;
    md += `- [ ] **Object Storage**: S3-compatible buckets for raw media (AWS S3, Cloudflare R2).\n`;
  }

  if (data.updateFrequency === 'Real-time or constant streaming') {
    md += `- [ ] **Streaming/Ingestion**: Setup Apache Kafka, Redis Streams, or RabbitMQ for real-time document sync.\n`;
  } else {
    md += `- [ ] **Ingestion**: Setup standard Cron jobs or periodic Airflow/Dagster syncs.\n`;
  }

  // 3. Integrations
  md += `\n## 3. Integrations\n`;
  if (data.integrations === 'Our own custom/proprietary internal databases and APIs') {
    md += `- [ ] **Connectors**: Develop custom REST/GraphQL bridges or strict \`MCP\` (Model Context Protocol) servers.\n`;
    md += `- [ ] **Network**: Configure VNet peering, VPNs, or API Gateway VPC Links to access internal data.\n`;
  } else if (data.integrations === 'Standard tools (Salesforce, Google Drive, Hubspot)') {
    md += `- [ ] **Connectors**: Use standard OAuth2 wrappers (e.g., \`Airbyte\`, \`n8n\` nodes, or native LlamaIndex loaders).\n`;
  }

  // 4. Security & Compliance
  md += `\n## 4. Security & Compliance\n`;
  if (data.dataSensitivity === 'Highly sensitive (Medical, Financial, Strictly Regulated)') {
    md += `- [ ] **Network**: Implement Zero-Trust Network Access (ZTNA), strict firewall rules, and Private Link/Endpoints.\n`;
    md += `- [ ] **Encryption**: Enforce BYOK (Bring Your Own Key), Data at Rest (AES-256), and TLS 1.3 everywhere.\n`;
    md += `- [ ] **Auditing**: Setup comprehensive SIEM logging, SOC2/HIPAA compliance tracing, and DLP (Data Loss Prevention).\n`;
  } else if (data.dataSensitivity === 'Internal company data (Confidential)') {
    md += `- [ ] **Network**: Standard WAF (Web Application Firewall, e.g., Cloudflare/AWS WAF).\n`;
    md += `- [ ] **Encryption**: Managed KMS keys for API credentials and databases.\n`;
  } else {
    md += `- [ ] **Network**: Standard HTTPS enforcement and basic rate limiting.\n`;
  }

  // 5. User Interface (Channels)
  md += `\n## 5. User Interface & Channels\n`;
  if (data.userInterface === 'WhatsApp or Telegram') {
    md += `- [ ] **Channel API**: Register and configure Meta Graph API (WhatsApp Business) or Telegram Bot API webhooks.\n`;
    md += `- [ ] **Middleware**: Implement state-machine or \`n8n\` webhook routers to manage chat sessions.\n`;
  } else if (data.userInterface === 'A chat widget on our website') {
    md += `- [ ] **Frontend**: Implement React/Next.js embeddable widget or use a white-label widget solution.\n`;
    md += `- [ ] **WebSockets**: Optionally deploy a dedicated Push/WebSocket service (e.g., Socket.io or AWS API Gateway WSS) for streaming responses.\n`;
  } else {
    md += `- [ ] **Frontend**: Build a custom full-stack web application (Next.js/Astro) with authenticated routes.\n`;
  }

  return md;
}
